### ISSUE TITLE
FR - Calculators page: Add additional pairs

### ISSUE THREAD

**Issue by adavibesp** [ADA-Ocean-Australia/adatools.io-support#2]
Hi,

Would it be possible to add additional currencies to the calculator. 

FYI I would go with adding those that have direct trading pairs available on the major exchanges as it would be easiest and most correct.

ADAVibe Ops

**Comment by CyberCyclone** [comment]
That's definitely the plan. We added the ADA->USD, USD->ADA yesterday just to get something in while we work on the more feature rich calculators. Coingecko supports the following currencies so we'll be adding calculators for the below. If there's a currency that you want that's not listed below then let us know and we'll look into it.

[
  "btc",
  "eth",
  "ltc",
  "bch",
  "bnb",
  "eos",
  "xrp",
  "xlm",
  "link",
  "dot",
  "yfi",
  "usd",
  "aed",
  "ars",
  "aud",
  "bdt",
  "bhd",
  "bmd",
  "brl",
  "cad",
  "chf",
  "clp",
  "cny",
  "czk",
  "dkk",
  "eur",
  "gbp",
  "hkd",
  "huf",
  "idr",
  "ils",
  "inr",
  "jpy",
  "krw",
  "kwd",
  "lkr",
  "mmk",
  "mxn",
  "myr",
  "ngn",
  "nok",
  "nzd",
  "php",
  "pkr",
  "pln",
  "rub",
  "sar",
  "sek",
  "sgd",
  "thb",
  "try",
  "twd",
  "uah",
  "vef",
  "vnd",
  "zar",
  "xdr",
  "xag",
  "xau"
]

**Comment by adavibesp** [comment]
That's great. You can close this issue if you want.

PS. Been having fun on Codingame, adding later this week.
