### ISSUE TITLE
Don't see my new testnet pool [ ₳Py🥧 ]

### ISSUE THREAD

**Issue by bourkefloyd** [ADA-Ocean-Australia/adatools.io-support#3]
Don't see my new testnet pool [ ₳Py🥧 ]

(select testnet at the bottom of the page)
https://pooltool.io/pool/f14dba9b7ca93790cb28de058b2135af1bf6f27e620eff6a38b44e98/delegators

Was trying to use your tool also to check on my pool and I couldn't find it

**Comment by CyberCyclone** [comment]
There's an issue with the meta URL not working. So the pool name isn't appearing. 

https://testnet.adatools.io/pools/f14dba9b7ca93790cb28de058b2135af1bf6f27e620eff6a38b44e98

**Comment by bourkefloyd** [comment]
looks like its working now
