### ISSUE TITLE
same issue with mainnet around not discovering my metadata. works fine on all other tools + daedalus 

### ISSUE THREAD

**Issue by bourkefloyd** [ADA-Ocean-Australia/adatools.io-support#4]
https://adatools.io/pools/9f2ed1ccecf4860081641cae0035525c929506d0d405e0261c184ba6

**Comment by CyberCyclone** [comment]
I've looked into it and fixed it so your pool is displaying now. Please check and verify that it's working as expected.

**Comment by bourkefloyd** [comment]
lgtm thanks!
