### ISSUE TITLE
Testnet-Pool GPOOL still not crawled

### ISSUE THREAD

**Issue by ghandmann** [ADA-Ocean-Australia/adatools.io-support#8]
Hi there,

i've got a testnet pool with ticker [GPOOL](https://testnet.adatools.io/pools/383905d4c9923fd5c940d6eb0bf88bb622b595cf057819ecc5e042dc) which was registered like 5 days ago. But the AdaTools-Page still reports it as "not crawled yet".

Is there anything wrong with my pool or with your crawling?

**Comment by CyberCyclone** [comment]
Hi mate,

The crawler has been stalling a bit since the hard fork as it required a major version change in cardano-graphql. I've restarted the crawler and I'll keep an eye on it for a bit. If your pool is not crawled in the next hour I'll have a look into it.

**Comment by ghandmann** [comment]
Now everything shows up! Thanks!
