### ISSUE TITLE
ADACT relays info inaccurate

### ISSUE THREAD

**Issue by adacapital** [ADA-Ocean-Australia/adatools.io-support#9]
Hi there,

One of my relays is showing as unreachable when in reality it has 17 outbound connections and 3 inbound connections.
Its IP is 51.105.18.17
https://adatools.io/pools/22ab39540db22349b1934f5dcb7788440c33709ea9fdac07fb343395

Kind regards,
Thomas
ps: adatools rock!

**Comment by CyberCyclone** [comment]
I'll be releasing an update that improves the crawl rate. Currently there's 3000 pools to crawl data on so it can take a while. 

I'll keep an eye on it and I'll post back in a few hours if it's fixed / updated.

**Comment by adacapital** [comment]
Cheers Casey, much appreciated, I owe you a beer!

**Comment by CyberCyclone** [comment]
It looks like everything is fine now. Let me know if there's any further issues related to this.

Thanks for reporting!
